language: android
jdk: oraclejdk8

android:
    components:
        - tools
        - platform-tools
        - tools

        - build-tools-25.0.2
        - android-25

#as per http://blog.travis-ci.com/2014-12-17-faster-builds-with-container-based-infrastructure/
sudo: false

notifications:
    email: false
